[package]
name = "shadcn-ui-yew-separator"
description = "Yew port of shadcn/ui Separator."
homepage = "https://shadcn-ui.rustforweb.org/components/separator.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
radix-yew-separator = { git = "https://github.com/RustForWeb/radix" }
tailwind_fuse.workspace = true
yew.workspace = true
