[package]
name = "shadcn-ui-yew-breadcrumb"
description = "Yew port of shadcn/ui Breadcrumb."
homepage = "https://shadcn-ui.rustforweb.org/components/breadcrumb.html"
publish = false

authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
lucide-yew = { workspace = true, features = ["arrows", "layout"] }
radix-yew-icons = { workspace = true }
tailwind_fuse.workspace = true
yew.workspace = true
yew-struct-component.workspace = true
yew-style.workspace = true
