[book]
authors = ["DaniÃ«lle Huisman"]
language = "en"
multilingual = false
src = "src"
title = "Rust shadcn/ui"

[preprocessor.tabs]

[preprocessor.trunk]

[output.html]
additional-css = ["theme/tabs.css", "theme/theme.css"]
additional-js = ["theme/tabs.js", "theme/theme.js"]
edit-url-template = "https://github.com/RustForWeb/shadcn-ui/edit/main/book/{path}"
git-repository-url = "https://github.com/RustForWeb/shadcn-ui"

[output.trunk]
serve = true

[rust]
edition = "2021"
